name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.78
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92373d'
    - '#4b362e'
    - '#c8cdcf'
    - '#ad7e70'
    - '#9a565b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
